x-ollama-default: &ollama-default
  image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
  pull_policy: always
  tty: true
  restart: unless-stopped
  volumes:
    - ollama:/root/.ollama
  environment:
    OLLAMA_MAX_LOADED_MODELS: 10
    OLLAMA_MAX_QUEUE: 20
    OLLAMA_NUM_PARALLEL: 1
  # GPU support
  deploy:
    resources:
      reservations:
        devices:
          - driver: ${OLLAMA_GPU_DRIVER-nvidia}
            capabilities: [ gpu ]
            #              count: ${OLLAMA_GPU_COUNT-1}
            #              count: all
            device_ids:
              - '0'
#                - '1'
#                - '2'
#                - '3'
#                - '4'
#                - '5'




services:
  ollama-1:
    <<: *ollama-default
    container_name: ollama-1
  ollama-2:
    <<: *ollama-default
    container_name: ollama-2

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - /storage/open-webui/backend_data:/app/backend/data
    depends_on:
      - ollama-1
      - ollama-2
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      #      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_BASE_URLS: "http://ollama-1:11434;http://ollama-2:11434"
      WEBUI_SECRET_KEY:
      USE_CUDA_DOCKER: 1
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  db:
    image: postgres:16.3
    shm_size: 256mb
    restart: always
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  ollama: { }
  postgres_data: { }
#  open-webui: {}
